### ISSUE TITLE
Data preprocess for NW-UCLA

### ISSUE THREAD

**Issue by erinchen824** [kchengiva/DecoupleGCN-DropGraph#1]
Hi, there, could you please provide the prepocessing code for NW-UCLA dataset? 
I have looked for the code of paper 'An Attention Enhanced Graph Convolutional LSTM Network for Skeleton-Based Action Recognition', but it seems they didn't release the code as well.

Thanks!

**Comment by erinchen824** [comment]
> Hi, there, could you please provide the prepocessing code for NW-UCLA dataset?
> I have looked for the code of paper 'An Attention Enhanced Graph Convolutional LSTM Network for Skeleton-Based Action Recognition', but it seems they didn't release the code as well.
> 
> Thanks!

Could you please elaborate a little bit about the structure of the skeleton data?
The sample skeleton data is like 

`60`

`-1.28173,0.389313,3.35539,2`
`-1.31799,0.467292,3.35571,2`
`-1.37781,0.863602,3.28662,2`
`-1.464,0.983077,3.16874,2`
`-1.34825,0.732381,3.15587,1`
`-1.37528,0.443887,3.14596,1`
`-1.51467,0.432556,3.37891,2`
`-1.52018,0.38395,3.4269,1`
`-1.22927,0.762531,3.37305,2`
`-1.31662,0.488039,3.23977,2`
`-1.37798,0.271541,3.29659,2`
`-1.36233,0.206601,3.32117,1`
`-1.30539,0.330782,3.38349,2`
`-1.37014,-0.196316,3.46889,2`
`-1.35937,-0.533079,3.47509,1`
`-1.36485,-0.60008,3.45439,1`
`-1.2419,0.345037,3.35064,2`
`-1.29558,-0.0525916,3.60391,2`
`-1.32793,-0.445877,3.48789,2`
`-1.37887,-0.528446,3.45204,2`


The first line seems like some indicator to a subject or a frame, the following lines shows the 3D coordinates of the joints, however, there are '1' and '2' occasionally appeared in the end of each line. Could you please enlighten me about what this data mean? 
Due to the lack of GPU, I need to start training from a small dataset like NW-UCLA. 
Looking forward to your reply.
Thanks!

**Comment by kchengiva** [comment]
Thanks for your interest.
We update our repo. You can `git clone` the new repo and run `CUDA_VISIBLE_DEVICES="0" python main.py --config ./config/nw-ucla/train_nwucla_*.yaml` to train on NW-UCLA dataset, where `*` is the stream name. Note that the `/home/share/NW-UCLA/data/all_sqe/` in `./feeders/feeder_nw.py` is your directory for NW-UCLA dataset. The preprocess of NW-UCLA dataset is borrow from Chenyang Si, the author of "An Attention Enhanced Graph Convolutional LSTM Network for Skeleton-Based Action Recognition". The trained model is provided as `./save_models/nw-ucla_joint.pt`.

**Comment by erinchen824** [comment]
> Thanks for your interest.
> We update our repo. You can `git clone` the new repo and run `CUDA_VISIBLE_DEVICES="0" python main.py --config ./config/nw-ucla/train_nwucla_*.yaml` to train on NW-UCLA dataset, where `*` is the stream name. Note that the `/home/share/NW-UCLA/data/all_sqe/` in `./feeders/feeder_nw.py` is your directory for NW-UCLA dataset. The preprocess of NW-UCLA dataset is borrow from Chenyang Si, the author of "An Attention Enhanced Graph Convolutional LSTM Network for Skeleton-Based Action Recognition". The trained model is provided as `./save_models/nw-ucla_joint.pt`.

Thanks for your update,  truly appreciate your timely help！

**Comment by erinchen824** [comment]
> Thanks for your interest.
> We update our repo. You can `git clone` the new repo and run `CUDA_VISIBLE_DEVICES="0" python main.py --config ./config/nw-ucla/train_nwucla_*.yaml` to train on NW-UCLA dataset, where `*` is the stream name. Note that the `/home/share/NW-UCLA/data/all_sqe/` in `./feeders/feeder_nw.py` is your directory for NW-UCLA dataset. The preprocess of NW-UCLA dataset is borrow from Chenyang Si, the author of "An Attention Enhanced Graph Convolutional LSTM Network for Skeleton-Based Action Recognition". The trained model is provided as `./save_models/nw-ucla_joint.pt`.

Seems like I still got trouble in preprocessing the NW-UCLA data.  
I don't have the json files used in the 'feeder_nw.py'. 
T^T
Since Chenyang Si, the author of "An Attention Enhanced Graph Convolutional LSTM Network for Skeleton-Based Action Recognition", didn't release their code and specify the preprocessing process.
The only thing for sure is first two view for training and the last view for test.

BTW, the number of classes for NW-UCLA is 10, however, in the config files, it is 28, is that correct?

`model_args:`
  `num_class: 28`

Thx!

**Comment by kchengiva** [comment]
Thanks for your interest. The raw NW-UCLA data can be downloaded [here](https://www.dropbox.com/s/10pcm4pksjy6mkq/all_sqe.zip?dl=0). The number of classes should be set to 10. Setting to 28 is a mistake, but it does not affect the results. Thank you for your correction.

**Comment by erinchen824** [comment]
> Thanks for your interest. The raw NW-UCLA data can be downloaded [here](https://www.dropbox.com/s/10pcm4pksjy6mkq/all_sqe.zip?dl=0). The number of classes should be set to 10. Setting to 28 is a mistake, but it does not affect the results. Thank you for your correction.

Thanks for your update, I think I'll be all set.
