### ISSUE TITLE
Pre-trained models!

### ISSUE THREAD

**Issue by tailin1009** [kchengiva/DecoupleGCN-DropGraph#2]
Hi Ke:
Can I have your models trained on the other three streams?  
- bone
- joint motion
- bone motion

Because I can't get the same results as shown in your paper(96.6%). There is a little gap(96.35~).
I need your reported models for benchmarking.

Thanks!

**Comment by kchengiva** [comment]
I'm sorry I couldn't be more helpful. We have deleted other saved models on our server.

**Comment by tailin1009** [comment]
> I'm sorry I couldn't be more helpful. We have deleted other saved models on our server.

Never mind！
Thanks for your reply！
