### ISSUE TITLE
Difference between SemGCN

### ISSUE THREAD

**Issue by ZJJTSL** [kchengiva/DecoupleGCN-DropGraph#4]
hi, i've noticed that you mentioned the difference between the SemGCN, and at the second point ,"our DC-GCN has non-local receptive fields" ,"The receptive field of SemGCN is localized" , i wonder how to understand this point .Thanks a lot !

**Comment by kchengiva** [comment]
Thanks for your interest. As stated in our paper, our DC-GCN has non-local receptive fields, where the learnable adjacent matrix models dense-connected graph. The receptive field of  Semantic Graph Convolution is localized, where the adjacent matrix models local relations between nodes. An extra non-local module is inserted in SemGCN for non-local modeling, introducing extra computation cost. Please refer to SemGCN paper for details.

**Comment by ZJJTSL** [comment]
Thanks for your reply. But i still can not figure it out that the differences between the DGCN(non-local receptive fields) and channel-wise SemGCN(localized receptive field), in the DGCN ,you seperate the channels into some groups,which is not used in SemGCN. Besides, i doubt why the skeleton-based graph is  dense-connected in DGCN . Could you please explain these in detail. Thanks a lot  for your generous help!

**Comment by kchengiva** [comment]
The local-connected graph is heuristically predefined and represents only the physical structure of the human body, which is not optimal for skeleton action recognition. For example, the relation between two hands is important for recognizing actions such as “clapping” and “reading”, but two hands are far from each other in human physical topology. Dense-connected graph with group decoupling mechanism covers non-local receptive field with no extra computational cost and a few extra parameters.
